### PR TITLE
docs: angular support

### PR DESCRIPTION
**Pull request by vltansky**
Hi, would be happy for review. Maybe I missed something or its not clear. It's kind of first time for me to write docs :)
I will add examples (stackblitz/codesandbox) later.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks, seems to be all good. Merged

**Comment by nolimits4web** [comment]
Please don't forget about examples, as it would be hard for me :)

**Comment by vltansky** [comment]
I'll be able to create examples only after the angular package will be published.
Maybe you want to publish `@next` version? Then I'll be able to work on examples and also to check that everything works.

**Comment by nolimits4web** [comment]
I published it yesterday https://unpkg.com/browse/skeleton-elements@3.1.0/ 🙂

**Comment by vltansky** [comment]
ah, ok, didn't know that.
So I'll make a PR tomorrow.

**Pull request merged**
